server:
  port: 9094
 
spring:
  application:
    name: employee-application  

eureka:
  instance:
    appname: employee-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://http://ec2-3-84-23-160.compute-1.amazonaws.com:9092/eureka/
      



              