server:
  port: 9092
 
spring:
  application:
    name: employee-application  

eureka:
  instance:
    appname: employee-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      



              