server:
  port: 9094
 
spring:
  application:
    name: employeeBenefits-application  

eureka:
  instance:
    appname: employeeBenefits-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
              