server:
  port: 9093
  
 
eureka:
  instance:
    appname: documentation-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-84-23-160.compute-1.amazonaws.com:9092/eureka/
      
swagger: 
  config: 
    refreshrate: 5000